name: Build and deploy redirect service

on:
  push:
    branches:
      - master
    paths: 
      - 'BusTracker-Redirect/**'
      - '.github/workflows/deploy-redirect.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'BusTracker-Redirect/**'
      - '.github/workflows/deploy-redirect.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build API project only
        run: dotnet build ./BusTracker-Redirect/BusTracker-Redirect.csproj --configuration Release

      - name: Publish API project
        run: dotnet publish ./BusTrackerServices/BusTracker-Redirect.csproj -c Release -r win-x86 --self-contained false -o publish /p:DeleteExistingFiles=true

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # OIDC Authentication, no secrets needed
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bustracker-redirect'
          slot-name: 'Production'
          package: dist



